# Usar la imagen oficial de Eclipse Mosquitto
FROM eclipse-mosquitto:latest

# Copiar los archivos de configuración al contenedor
COPY mosquitto.conf /mosquitto/config/mosquitto.conf
COPY passwd /mosquitto/config/passwd
